server:
  port: 7777
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # default false
      routes:
        - id: user-profile-service-route
          uri: lb://USER-PROFILE-SERVICE
          filters:
          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          predicates:
            - Path=/api/profiles/**
        - id: admin-service-route
          uri: lb://ADMIN-SERVICE
          filters:
          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          predicates:
            - Path=/api/admin/**
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
    logging:
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
      level:
        root: TRACE

logging:
  level:
    org:
      springframework:
        web: TRACE
springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    use-root-path: true
    urls:
      - name: user-profile
        url: /v3/api-docs/api/profiles
      - name: admin
        url: /v3/api-docs/api/admin
