server:
  port: 8060
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true