server:
  port: 6666

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
feign:
  client:
    config:
      default:
        readTimeout: '5000'
        connectTimeout: '5000'
        loggerLevel:
spring:
  sql:
    init:
      mode: always
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/skillstracker2
    username: root
    password: pass
  jpa:
    defer-datasource-initialization: false
    generate-ddl: on
    show-sql: true
  properties:
    hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: create-drop

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  logging:
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    level:
      root: INFO
logging:
  level:
    org:
      springframework:
        web: INFO
