server:
  port: 3333

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
feign:
  client:
    config:
      default:
        readTimeout: '5000'
        connectTimeout: '5000'
        loggerLevel:
spring:
  datasource:
   # url: jdbc:h2:file:/skillstracker;AUTO_SERVER=TRUE
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/skillstracker2
    username: root
    password: pass

  jpa:
    defer-datasource-initialization: false
    show-sql: true
    generate-ddl: on
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: create-drop
#  h2:
#    console:
#      enabled: true
#      # default
#      path: /h2-console
#      #path: /h2-ui
#      settings:
#        web-allow-others: true

  logging:
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    level:
      root: TRACE